import '../design-system/utils/globals.css';
import type { Metadata } from "next";
import "./globals.css";
import BreadcrumbProvider from "@/design-system/components/BreadcrumbProvider";
import { Geist, Geist_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-background dark:bg-background-dark`} style={{ fontFamily: 'Raleway, sans-serif' }}>
        <BreadcrumbProvider>{children}</BreadcrumbProvider>
      </body>
    </html>
  );
}
